# Generated by Django 3.1.6 on 2021-02-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='text',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='text',
            new_name='name',
        ),
    ]
